# Generated by Django 4.2 on 2023-05-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
